server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    suffix: .html

  ssl:
    bundle:
      pem:
        emoji-api:
          keystore:
            certificate: "classpath:emojiclientcertlocal.pem"
            private-key: "classpath:client-private-key.pem"
            private-key-password: "password"
          truststore:
            certificate: "classpath:emojiapicertlocal.pem"

---

spring:
  config:
    activate:
      on-profile: https

emoji:
  port: 8443
  scheme: https


---

spring:
  config:
    activate:
      on-profile: http

emoji:
  port: 8081
  scheme: http