server:
  port: 8080

spring:
  thymeleaf:
    cache: false
    suffix: .html

#  ssl:
#    bundle:
#      pem:
#        emoji-api:
#          keystore:
#            certificate: "classpath:consumercert.pem"
#            private-key: "classpath:consumer-private-key.pem"
#            private-key-password: "password"
#          truststore:
#            certificate: "classpath:apicert.pem"

---

spring:
  config:
    activate:
      on-profile: https

emoji:
  port: 8443
  scheme: https

mtls:
  enabled: true
  private-key-passwd: "password"


---

spring:
  config:
    activate:
      on-profile: http

emoji:
  port: 8081
  scheme: http