spring:
  profiles:
    active: local

server:
  port: 8443
  ssl:
    key-store: classpath:server-keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: emoji-api
    enabled: true
#    trust-store-password: password
#    trust-store: classpath:emojiapi.truststore
#    trust-store-type: JKS
    client-auth: none
#    client-auth: need